
////////////////////////////////////////////////////////////
// SETTINGS
////////////////////////////////////////////////////////////

//cards settings
var cardsSettings = [

  {
    assets:{
      landscape:{
        background:'assets/card_bg_landscape.png',
        logo:'assets/card_logo_landscape_2.png',
        scratch:'assets/card_scratch_landscape_2.png',
      },
      portrait:{
        background:'assets/card_bg_portrait.png',
        logo:'assets/card_logo_portrait_2.png',
        scratch:'assets/card_scratch_portrait_2.png',
      },
    },
    matchedItems:3,
    numbers:[],
    bonusMax:0,
    overallPercent:100,
    price:{
      value:5,
      x:25,
      y:50
    },
    items:[
      {
        x:114,
        y:130,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:220,
        y:130,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:330,
        y:130,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:430,
        y:130,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:114,
        y:225,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:220,
        y:225,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:330,
        y:225,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:430,
        y:225,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:114,
        y:320,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:220,
        y:320,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:330,
        y:320,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
      {
        x:430,
        y:320,
        width:15,
        height:15,
        image:{
          offsetX:0,
          offsetY:0,
        },
        prize:{
          offsetX:0,
          offsetY:0,
        },
        number:{
          offsetX:0,
          offsetY:0,
          fontSize:30,
          lineHeight:10,
          color:'#2E303A',
        },
        type:'prize'
      },
    ],
    prizes:[
      {
        value:1,
        text:{
          display:'$1',
          fontSize:32,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:50,
      },
      {
        value:5,
        text:{
          display:'$5',
          fontSize:32,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:10,
      },
      {
        value:10,
        text:{
          display:'$10',
          fontSize:32,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:5,
      },
      {
        value:100,
        text:{
          display:'$100',
          fontSize:25,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:1,
      },
      {
        value:500,
        text:{
          display:'$500',
          fontSize:25,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:0,
      },
      {
        value:1000,
        text:{
          display:'$1,000',
          fontSize:20,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:0,
      },
      {
        value:2500,
        text:{
          display:'$2,500',
          fontSize:20,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:0,
      },
      {
        value:5000,
        text:{
          display:'$5,000',
          fontSize:20,
          lineHeight:0,
          color:'#2E303A',
        },
        image:'',
        percent:0,
      },
    ],
    bonus:[],
    symbols :[]
  }
];

//game settings
var gameSettings = {
  score:{ //score position
    x:100,
    y:0
  },
  credit:100, //start credit
  scratchStrokeNum:[20,30], //scratch stroke number
  revealScratchStrokeNum:[25,35], //scratch stroke number
  revealSpeed:.1, //reveal speed
  revealCurviness:2, //reveal curviness
  winColorFilter:[140,35,0],
  enablePercentage:true, //option to have result base on percentage
};

//game test display
var textDisplay = {
  price:"$[NUMBER]",
  buy:'Jugar $[NUMBER]',
  buyAgain:'Usar $[NUMBER]',
  scratch:'Raspa tu carta...',
  noCredit:'Ya no te quedan créditos...',
  won:'+$[NUMBER]',
  exitTitle:"Salir",
  exitMessage:'Está seguro/a \nque deseas\nsalir del juego?',
  resultTitle:"Ganaste un total de",
  share:'Retirar Ganancias',
  resultDesc:'$[NUMBER]'
};

//Social share, [SCORE] will replace with game score
var shareEnable = false; //toggle share
var shareTitle = 'Highscore on Scratch & Win is $[SCORE]';//social share score title
var shareMessage = '$[SCORE] is mine new highscore on Scratch & Win game! Try it now!'; //social share score message
